services:
  db:
    image: postgres:17
    container_name: postgres-db
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: fastapi-backend
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

  frontend:
    build: ./frontend
    container_name: react-frontend
    env_file:
    - .env
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:80"

volumes:
  pg_data:
